# Generated by Django 5.2.6 on 2025-09-06 10:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='클라이언트/게이트웨이에서 제공하는 멱등 키(X-Idempotency-Key 등). 유니크합니다.', max_length=200, unique=True, verbose_name='멱등 키')),
                ('request_hash', models.CharField(db_index=True, help_text='요청 바디/주요 파라미터의 해시. 동일 키 재사용 시 내용 일치 여부 검증에 사용.', max_length=200, verbose_name='요청 해시')),
                ('response_body', models.TextField(blank=True, help_text='이미 처리된 요청의 응답(JSON 직렬화 문자열 등)을 보관합니다.', verbose_name='응답 캐시')),
                ('status_code', models.IntegerField(db_index=True, default=0, help_text='처리 시의 HTTP 상태 코드(0=미처리/미정).', verbose_name='상태 코드')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='키가 생성된 시각입니다. 보관 정책에 따라 정리하세요.', verbose_name='생성 시각')),
            ],
            options={
                'verbose_name': '멱등 키',
                'verbose_name_plural': '멱등 키',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status_code', 0), models.Q(('status_code__gte', 100), ('status_code__lte', 599)), _connector='OR'), name='idemp_status_code_valid')],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='URL/서브도메인 등에 쓰는 슬러그(예: acme, foo-bar). 생성 후 변경을 피하는 것을 권장합니다.', unique=True, verbose_name='테넌트 코드')),
                ('name', models.CharField(help_text='사람이 읽는 이름(회사/조직명).', max_length=200, verbose_name='테넌트 이름')),
            ],
            options={
                'verbose_name': '테넌트',
                'verbose_name_plural': '테넌트',
                'indexes': [models.Index(fields=['name'], name='tenant_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='레코드가 생성된 시각입니다.', verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 저장될 때마다 자동 갱신됩니다.', verbose_name='수정 시각')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='이벤트 레코드의 전역 고유 식별자(UUID).', primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, help_text='예: "user.created", "invoice.paid" 등 이벤트 타입 식별자.', max_length=200, verbose_name='이벤트 이름')),
                ('payload', models.JSONField(help_text='이벤트 본문(JSON). 스키마는 애플리케이션 계약으로 관리합니다.', verbose_name='페이로드')),
                ('published', models.BooleanField(db_index=True, default=False, help_text='퍼블리셔가 처리 완료하면 True로 마킹합니다.', verbose_name='발행 여부')),
                ('tenant', models.ForeignKey(help_text='이 레코드가 속한 테넌트입니다. 테넌트 삭제 시 보호(PROTECT)됩니다.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant', verbose_name='소속 테넌트')),
            ],
            options={
                'verbose_name': '아웃박스 이벤트',
                'verbose_name_plural': '아웃박스 이벤트',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant', 'published', 'created_at'], name='outbox_poll_idx'), models.Index(fields=['tenant', 'event_name', 'published'], name='outbox_event_idx')],
            },
        ),
    ]
