# Generated by Django 5.2.6 on 2025-09-17 10:55

from django.db import migrations

def ensure_public_member(apps, schema_editor):
    Tenant = apps.get_model("core", "Tenant")
    Role = apps.get_model("accounts", "Role")
    tenant, _ = Tenant.objects.get_or_create(code="public", defaults={"name": "Public"})
    Role.objects.get_or_create(tenant=tenant, code="member", defaults={"name": "일반회원"})

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("accounts", "0001_initial"),
    ]
    operations = [
        migrations.RunPython(ensure_public_member, migrations.RunPython.noop),
    ]
